### ISSUE TITLE
Hoobs doesnt restart after installation of Aircast module

### ISSUE THREAD

**Issue by danlun** [artificialhoney/aircast#1]
Hi, Just installed this module on Hoobs (Homebridge) but my installation wont restart after the installation. The config is updated, first with only "platform": "Aircast" and testing with this only, just restarted the PI machine and Hoobs but the Hoobs service dont start. Looked at the guide and added "name": "Aircast",
"url": "http://localhost:9000/api/"
in the configuration but it didnt help.
This is the logfil

[Homebridge] [3/28/2020, 5:34:52 AM] Loaded config.json with 0 accessories and 3 platforms.
[Homebridge] [3/28/2020, 5:34:52 AM] Plugin /home/hoobs/.hoobs/node_modules/homebridge-aircast requires Node version of ^6.9.1 which does not satisfy the current Node version of v12.14.1. You may need to upgrade your installation of Node.
[Homebridge] [3/28/2020, 5:34:53 AM] Loaded plugin: "homebridge-aircast"
[Homebridge] [3/28/2020, 5:34:53 AM] Registering platform "homebridge-aircast.Aircast"
[Homebridge] [3/28/2020, 5:34:53 AM] Loaded plugin: "homebridge-telldus"
[Homebridge] [3/28/2020, 5:34:53 AM] Registering platform "homebridge-telldus.Telldus"
[Homebridge] [3/28/2020, 5:34:53 AM] Loaded plugin: "shelly"
[Homebridge] [3/28/2020, 5:34:54 AM] Registering platform "homebridge-shelly.Shelly"
[Homebridge] [3/28/2020, 5:34:54 AM] Loading 3 platforms...
[Homebridge] [3/28/2020, 5:34:54 AM] [Telldus Liv!e] Initializing Telldus platform...
[Homebridge] [3/28/2020, 5:34:54 AM] [Telldus Liv!e] isLocal: false
[Homebridge] [3/28/2020, 5:34:54 AM] [Telldus Liv!e] Loading accessories...
[Homebridge] [3/28/2020, 5:34:54 AM] [Shelly] Initializing Shelly platform...
[Homebridge] [3/28/2020, 5:34:54 AM] [Aircast] Initializing Aircast platform...
[Homebridge] [3/28/2020, 5:34:54 AM] [Aircast] Aircast Platform Plugin Version 0.1.6
[Homebridge] [3/28/2020, 5:34:54 AM] Loading 0 accessories...
[Homebridge] [3/28/2020, 5:34:54 AM] [Shelly] 1 accessory loaded from cache
[Homebridge] [3/28/2020, 5:34:55 AM] API launched
[Homebridge] [3/28/2020, 5:34:55 AM] [Shelly] Admin server is running on port XXXX
[Homebridge] [3/28/2020, 5:34:55 AM] [Shelly] Unknown device undefined undefined at 192.1XX.X.XX discovered
[Homebridge] [3/28/2020, 5:34:55 AM] Error: Error: connect ECONNREFUSED 127.0.0.1:9000
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-aircast/index.js:40:13)
    at Request.emit (events.js:223:5)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Homebridge] [3/28/2020, 5:34:55 AM] Got SIGTERM, shutting down service...
[Homebridge] [3/28/2020, 5:34:55 AM] [Telldus Liv!e] Found 0 sensors in telldus live.

if it helps

Thanks

**Comment by danlun** [comment]
Anyone?

**Comment by artificialhoney** [comment]
Hi Dan,

this module is not actively maintained anymore! The message says `Error: connect ECONNREFUSED 127.0.0.1:9000`. Did you start Aircast like described in the Readme? It is not sufficient to run only Hoobs (probably) you need to start Aircast like:

```shell
# installation
npm install aircast --global
# start
aircast
```

Best Regards
Sebastian

**Comment by danlun** [comment]
Ok, thanks Sebastian that might be the thing then. Sorry it’s not
maintained any longer. I will need to turn to HomeAssistant. The idea is
great though, especially if and when someone comes up with AirPlay 2.

Take care!

Dan

ons 1 apr. 2020 kl. 07:48 skrev Sebastian Krüger <notifications@github.com>:
